apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moonrhythm
  labels:
    app: moonrhythm
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: moonrhythm
  template:
    metadata:
      name: moonrhythm
      labels:
        app: moonrhythm
    spec:
      containers:
      - name: moonrhythm
        image: gcr.io/acoshift-1362/moonrhythm
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 5
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: moonrhythm
  labels:
    app: moonrhythm
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: moonrhythm
